rmwc/rmwc

- src/Menu/index.js
The noop defaults where actually only missing on the Select component :). 
Fixes: #49
> fix(menu): Add missing noop to onClose() & onSelect() callbacks

- src/index.js
Export GridInner to the global export. It's useful when dealing with multiple nested grids. Of course, for the time being, it is always possible to import: `import { GridInner } from 'rmwc/Grid';` as discussed on another occasion.
Maybe let's also add more info to the documentation? I had to look into the code to make sure what `<Grid/>` is doing.
> fix(LayoutGrid): export GridInner

- package.json
It is better to have those two defined as [`peerDependencies`](https://docs.npmjs.com/files/package.json#peerdependencies). Spotted the issue when tried to use [bundlephobia.com](https://bundlephobia.com/result?p=rmwc).
> Move react and react-dom to peerDependencies

- src/Select/index.js
PR to the discussion in #104. Need to figure out the desired behavior first. I will change this PR in case that changes to something other than showing the label / placeholder for value = null.
> fix(Select): Don't show first option if value = null

- src/Slider/index.js
Both mdc events :input and :change are mapped to onChange(). Adding an onInput() callback for the :input event. Fixing issue #118
> fix(slider): add onInput for sliding callback

- .gitignore
- src/Tabs/index.js
`Tab` being wrapped by an `HOC` like `styled-components` causing an Initialization loop because it's `displayName !== 'Tab'`.
Resolves #116
> fix(Tabs): HOC Tab Initialization loop

- src/GridList/grid-list.md
- src/GridList/grid-list.spec.js
- src/GridList/grid-list.story.js
- src/GridList/index.js
Adds a `<GridTileIcon>` component to take advantage of the `withIconAlignStart` prop on `<GridList>`. It uses the existing `<Icon>` component and adds the MDC class `mdc-grid-tile__icon` to the element.
> feat(GridList): add GridTileIcon

- src/TextField/index.js
- src/TextField/textfield.spec.js
Beforehand, the invalid prop in the react component is not synced with TextField Foundation
> Sync validality status with TextField Foundation

- src/Dialog/index.js
- src/docs/docgen.json
I noticed a couple of missing details in the documentation for the Dialog components. In particular, the `scrollable` prop for the DialogBody was not shown and the descriptions for the DialogFooterButton props were missing. This adds a flow type definition for the DialogBody and fixes a couple small typos in the DialogFooterButton prop type descriptions
> docs(Dialog): Missing props and descriptions

- src/TextField/index.js
When using the disabled property on textfield `mdc-text-field--disabled` should be added as a className. Fixes issue #147
> fix(textfield): add mdc class on disabled textfields

- src/Base/MDCFoundation.js
> Fix IE11 support for MDCFoundation

- src/docs/App.js
Currently the ThemeProvider example code shown in the TopAppBar of the docs is broken. It's missing the secondary braces and still imports from `rmwc/ThemeProvider` which - i guess - was moved to `rmwc/Theme`.
> Fix ThemeProvider example in docs

- src/top-app-bar/index.js
This PR corrects a typo in TopAppBarSection's className when alignStart=true so that proper style is applied.
> fix(TopAppBar): Corrects alignStart style for TopAppBarSection

- src/textfield/index.js
When textbox are marked as boxed or outlined, this margin is not applied, but it should not be applied also when textarea is set.
We can see the incorrect margin in demo of textareas, when the control receives focus:
https://jamesmfriedman.github.io/rmwc/text-fields
> fix(TextField): Textarea is including margin-top.

- src/snackbar/index.js
Relates to issue https://github.com/jamesmfriedman/rmwc/issues/345 
Warning: I don't know if this breaks anything. It looks reasonable to me but it's meant to be illustrative of my comment: https://github.com/jamesmfriedman/rmwc/issues/345#issuecomment-431858170
The `!!` are added to turn the type from `undefined | boolean` to just `boolean`.
Though it does build correctly.
> use SnackbarPropsT in syncWithProps parameter

- src/menu/index.js
- src/menu/menu.spec.js
We use RMWC for some of our web applications, and it recently underwent an audit for ADA compliance. Some of our dropdown menus were flagged as improperly using the aria-hidden attribute, as it was set to true regardless of whether or not the menu was open, and contained nested elements which were subsequently ignored by screen readers.
This PR fixes aria-hidden for the Menu component.
Here's the violation in our web app:
After fix:
> fix(Menu): Set aria-hidden dynamically for A11Y

- src/select/index.js
To activate the select on clicking the corresponding label, the label needs to have a for attribute with a matching id. Either by setting a random id, or providing one to the select.
> Add support for id and for attributes

- src/data-table/data-table.css
> fix(data-table): cell height of mdc-select

- src/list/README-COLLAPSIBLE.md
I'm assuming this needs to be fixed...
> 5.x Fixes typo in Collapsible List css path

- src/snackbar/package.json
As of v5.0.0 (specifically e8b617d) — the `<Snackbar />` imports and uses the `<IconButton />` for the `dismissIcon` prop, but `@rmwc/icon-button` was never added to the list of dependencies for `@rmwc/snackbar`. This PR adds the latest version to the dependencies list.
> fix(Snackbar): Add missing icon-button dependency

- src/dialog/index.tsx
Issue #445 
- If `acceptLabel` and `cancelLabel` are set to null, footer will still render
- Fixed footer rendering as an Object
> fix(Dialog): Render footer in SimpleDialog

- src/button/README.md
- src/button/index.tsx
An example for the trailing icon wasn't in the docs. Therefore I thought as a user that this possibility is not officially supported.
This PR adds it to the docs.
> add trailing icon example

- src/dialog/readme.tsx
- src/linear-progress/readme.tsx
- src/select/readme.tsx
The module names in the new docs for **dialog**, **linear-progress** and **select** seem to be incorrect.
Corrected them to **@rmwc/dialog**, **@rmwc/linear-progress** and **@rmwc/select**.
> Fix dialog, linear-progress and select module names in docs

- src/dialog/dialog-queue.tsx
- src/snackbar/snackbar-queue.tsx
* `import * as React from 'react'` syntax needs to be used to avoid breaking consumers
Fixes - https://github.com/jamesmfriedman/rmwc/issues/465
> fix(Dialog|Snackbar): broken dialog and snackbar types

- src/checkbox/checkbox.spec.tsx
- src/checkbox/index.tsx
- src/switch/index.tsx
- src/switch/switch.spec.tsx
- src/textfield/index.tsx
- src/textfield/textfield.spec.tsx
- src/toggleable/index.tsx
fixes #475 
1) update inputRef's type to allow for react's `MutableRefObject` in addition to functional ref captures for textfield, switch and checkbox components
2) added tests to ensure passing in both types are supported
> support react useRef with @rwmc's inputRef

- src/menu/menu.tsx
This PR adds an extra check to `isMenuItems` function to take into consideration the `type` of the element being checked. Previous implementation was breaking on `Symbol` and `string` element types, when used like this:
```jsx
<Menu>
{condition1 && (
<React.Fragment>
<Divider />
<MenuItem />
</React.Fragment>
)}
{condition2 && (
<div>
<Divider />
<MenuItem />
</div>
)}
</Menu>
```
This would cause the `in` operator to be executed on values of type `Symbol` and `string` respectively.
> Fix "isMenuItems" check to not break on Symbol and string element types.

- src/slider/index.tsx
If `props.value` and `props.max` change simultaneously (e.g. increasing both by 1) the out of bounds warnings are still logged. I have changed the order of syncing between value and max/min to avoid that.
> Slider: sync min/max props before value to avoid warnings.

- src/select/index.tsx
Fix bug: Placeholder disapears when value or defaultValue prop is set
> Bugfix #533

- CHANGELOG.md
Hey, it looks like the changelog for version 5.7.2 didn't include information about pull request #535, which fixed issue #533.
Realized this when we upgraded to 5.7.2 and some of our code that depended on the old behaviour broke.
So, just listed that change in the changelog too.
> Update 5.7.2 changelog with fix for issue #533

- src/theme/theme.css
Added a hotfix for the incorrect nav drawer list item graphic color when activated which is caused by a bug in mwc. Let me know if you have any questions.
> Added a hotfix for mdc style bug for issue #602

- src/elevation/index.tsx
As I see, `z` has default value. IMHO it should be optional. With required mode I see false positive warnings in my IDE
> Make z prop optional

- src/top-app-bar/index.tsx
- src/top-app-bar/top-app-bar.spec.tsx
It fixes #634 
This PR adds some tests for checking class names in `TopAppBarFixedAdjust` components and updates code to pass the tests
> fix(TopAppBar): Wrong className for TopAppBarFixedAdjust

- src/select/select/index.tsx
This bug did not allow MenuProps like "renderToPortal" to be forwarded to menu for enhanced select when passing in an object in "enhanced" prop.
> fix(Select): fixed menu props not forwarding for enhanced select

- src/top-app-bar/index.tsx
Hi,
I want to resolve this issue, #634. 
Since media query, className `mdc-top-app-bar--fixed-adjust` has higher priority than `.mdc-top-app-bar--dense-fixed-adjust` in `<TopAppBarFixedAdjust dense />`.
So, I want to add className `mdc-top-app-bar--fixed-adjust` when all props (dense, denseProminent, prominent, short) are undefined or false. 
Since the only css property that `mdc-top-app-bar--fixed-adjust` or `.mdc-top-app-bar--dense-fixed-adjust` manipulates is `padding-top`, I think this PR makes sense.
But, I know this PR makes the className `mdc-top-app-bar--fixed-adjust` loose its role as default className for `<TopAppBarFixedAdjust />`
In addition, I'm worried since this line need update if another property of `TopAppBarFixedAdjust` is created newly.
If you have more appropriate …
> fix(top-app-bar): Fix wrong className for TopAppBarAdjust

- src/rmwc/package.json
Right now the typings for e.g. `import { Button } from 'rmwc'` are not imported correctly.
> Fix typings for rmwc package

- package-lock.json
- src/base/foundation-component.tsx
- src/menu/menu.story.tsx
- src/select/select.story.tsx
Currently Menus and enhanced Select menus using renderToPortal to render the pop-up containing the menu items to a Portal are broken. Clicking menu items does nothing and the onSelect callback is never called.
This seemingly happens because the useFoundation() hook from @rmwc/base seems to set null as the apiRef/listApi reference in the Menu foundation when the cleanup function of the useEffect() hook in useFoundation() is called. The same useEffect() hook then never re-sets the listApi leaving it as null. This seems to only happen when renderToPortal is used for some reason. 
As a solution the useEffect() hook now sets the apiRef of components every time it is run in addition to the apiRef being set in the useMemo() hook. This seems to fix the behaviours of both type of menus. Does this …
> Fix clicking items in Menus and enhanced Select menus

- src/tabs/tab-foundation.tsx
- src/tabs/tab.tsx
- src/tabs/tabs.spec.tsx
This PR allows the tabs to be configured as to whether they should automatically focus when activated. This is set to true by default in MDC Web, but can be configured through the foundation.
When true, the active tab will immediately gain focus on page load. In this case it's the "Pizza" tab in "Always 1"
If we set the Tabs in the "Always 1" example to have `focusOnActivate={false}, then the focus will not be set on this set of tabs and focus will remain on the previous story that still has the default behavior.
Resolves: #557
> feat(Tab): Add ability to set focusOnActivate

- src/list/list.tsx
Allowing `wrapFocus` to remain in the `...rest` parameter will throw a react-dom warning about an unrecognized prop.
> Do not pass "wrapFocus" List prop to Tag

- src/snackbar/snackbar.tsx
Allows users to specify their own SVGs or images to use as the `Snackbar` dismiss icon. Mirrors the existing behavior of the `Icon` and `IconButton` components.
> fix(snackbar): support SVGs as dismiss icon

- src/icon/icon.spec.tsx
- src/icon/index.tsx
- src/types/index.tsx
A small PR to start my contribution for RMWC.
Minor change is that the custom render method of Icon component may no longer return a string or a number (`ReactText` type is now excluded from the `ReactNode` union type). However, that should not change compatiblity since the code would have crashed anyway if users would return a `string | number` from the custom render method. 
Now it will simply return null when the render method doesn't return a valid `ReactElement`.
> chore(Icon): Improve typings of icon render method

- src/textfield/styles.tsx
- src/textfield/textfield.css
Fixes an issue of date-picker not showing up with type="date". A result of this commit on material-components-web: https://github.com/material-components/material-components-web/commit/4951e7651ffbd99b382948e48306a23d2fd74fb1
> fix(textfield): Add back styling for date picker

- package.json
- src/types/index.tsx
Fixes issue when depending on RMWC 8.x. which says:
```
<Tag extends React.ElementType<any> = Element>(props: ComponentProps<Props, ElementsProps, Tag>, ref: any): JSX.Element;
Type 'Props' does not satisfy the constraint '{}'
```
> fix(type): Extends {} to fix error in declarations

- scripts/docgen-examples.js
- scripts/docgen-markdown.js
- scripts/docgen-props.js
- src/base/PortalContext.tsx
- src/base/README.md
- src/base/generated-examples.json
- src/base/index.spec.tsx
- src/base/index.tsx
- src/base/portal.tsx
- src/base/readme.tsx
- src/rmwc/docs/common/menu-content.tsx
- src/rmwc/docs/views/app/index.tsx
This PR is intended to solve #853.
Solution:
- Created a PortalContext to store the portal element and function to set element
- If PortalContext is not found, the Portal should work exactly the same as before
- Portal element will set `portalElement` in PortalProvider if PortalContext is found
- PortalChild will render to the `portalElementFromContext` if found and `renderTo` is `true`
- I added `PortalProvider` to `App` to demonstrate its capability
- I didn't add any tests, but all tests are still passing
Notes:
I believe this is my first PR for RMWC so I'm not expecting this to be approved, but am hoping it will be enough for the team to determine if this is an acceptable solution.
Since I was modifying an existing component, I didn't know if any other files were necessary. Please …
> feat(portal): Support Portal in a ShadowDom by using PortalContext

- nx.json
- package.json
- scripts/fix-dependency-versions.js
This ensures that the built packages have their dependency versions corrected from `workspace:*` to the current version
> fix: publish step should change dependency versions

- packages/tooltip/src/lib/__snapshots__/tooltip.spec.tsx.snap
- packages/tooltip/src/lib/tooltip.tsx
- setupTests.ts
Using crypto to generate id was not a good solution as it would generate a random id on every render. Not great for snapshot testing as well.... luckily James has been smart as always, and already created a proper `useId` hook! So I used that instead. Cheers.
> fix(tooltip): use correct unique id

- packages/icon-button/src/lib/icon-button.spec.tsx
- packages/ripple/src/lib/ripple.spec.tsx
- packages/ripple/src/lib/ripple.tsx
If one uses the `<Ripple />` component directly in their code, it will not adhere to ripple being set to false by the provider `<RMWCProvider ripple={false} />`. This PR is fixing this, so that `<Ripple />` will adhere to the provider.
> fix(ripple): have ripple adhere to provider

- packages/linear-progress/src/lib/foundation.tsx
When mounting and immediately unmounting an indeterminate `LinearProgress`, sometimes the following error is thrown:
```
Uncaught TypeError: Cannot read properties of null (reading 'style')
at Object.setStyle (index.mjs:41:1)
at MDCLinearProgressFoundation.calculateAndSetDimensions (foundation.js:193:1)
at ResizeObserver.eval (foundation.js:82:1)
```
Upon mounting, a resize observer is attached. This observer always triggers once after setup (expected behaviour of resize observers). With just the right timing, the callback is executed when the component has already been unmounted again.
Prevent the callback from being executed altogether if the element is not in the dom anymore.
Since this is a race condition, I wasn't able to reliably reproduce it and therefore added no tests.
> fix(linear-progress): prevent fast-unmount error

- packages/chip/package.json
- packages/chip/src/lib/foundation.tsx
- packages/chip/src/lib/index.tsx
Due to how we import deprecated chip, es modules cannot understand it. This is the fix.
> fix(chip): properly import deprecated chip

- packages/select/src/lib/__snapshots__/select.spec.tsx.snap
- packages/select/src/lib/select.spec.tsx
- packages/select/src/lib/select.story.tsx
- packages/select/src/lib/select/foundation.tsx
- packages/select/src/lib/select/index.tsx
This PR fixes three issues:
- When setting default value, the select would display the value and not the label. Now the correct text is set.
- onChange event would fire three times. Now it fires once.
- disabled prop was not passed correctly. It is now.
> fix(select): correctly set defaultvalue, onchange fire only once, disabled prop passed correctly

- packages/select/src/lib/select/index.tsx
While select is disabled, there is an error:
app-index.js:33 Warning: Expected onFocus listener to be a function, instead got false.
> fix(Select): Disable select issue for onFocus getting false instead of function
