rmwc/rmwc

src/TextField/index.js
=> fix(TextField): Rename helptext to helper-text to follow mwc

docs/content.js, src/Tabs/index.js, src/Tabs/tabs.spec.js, src/Tabs/tabs.story.js, src/index.js
Using MDCTabBarScroller from @material/tabs/dist/mdc.tabs.
=> feat(TabBarScroller): Adding TabBarScroller component.

src/Tabs/index.js, src/Tabs/tabs.story.js
=> fix(TabBar): reinit when adding/removing tabs dynamically.

src/Drawer/drawer.story.js
Change to the correct key `displayName` and add the icon as `<ListItemStartDetail>`
=> fix(drawer): list items don't show name and icon in story

package.json
=> Move react-scripts dep to devDependencies

.eslintrc.json, src/Base/simpleTag.js, src/docs/polyfills.js
=> Remove reliance on Reflect

ISSUE_TEMPLATE.md
I created a Sandbox for reproducing issues and bugs. Code always say more than a thousand words ; )
=> Add sandbox to issue template

src/Base/withMDC.js, src/Tabs/index.js, src/Tabs/tabs.md, src/Tabs/tabs.spec.js, src/Tabs/tabs.story.js
@izakfilmalter You were really close, thanks for looking into it. If you can pull this branch and validate I'll publish a quick patch.
=> fix(TabBar): activeTabIndex doesn't set active tab of 0 on load #94

src/docs/menuContent.js, src/docs/styled-components.md
@jamesmfriedman Let me know about writing style and examples.
=> enhancement(Docs): Add docs for styled-components.

src/docs/styling.md
=> fixed a typo, added 'see' to sentence

package-lock.json, package.json, src/Base/MDCFoundation.js, src/Base/testPolyfill.js, src/IconToggle/icon-toggle-ssr.spec.js, src/List/index.js, src/Ripple/ripple-ssr.spec.js, src/Select/index.js, src/Select/select.md, src/Slider/index.js, src/Slider/slider-ssr.spec.js, src/Slider/slider.spec.js
- Corrects a timing issue with the foundation components which prevents SSR
- Added tests for the new foundation components for server side rendering
=> fix(SSR): Corrects server side rendering for foundation based components

src/Menu/index.js
I think theres a small typo in this
=> Fixing typo in anchor corner

src/Card/index.js, src/TopAppBar/index.js, src/docs/docgen.json
=> chore(Docs): fixing typos

src/docs/methodology.md
=> Fix typo in Methodology docs

README.md
Fixed contributor image link in readme.
=> [minor] fix link in readme

src/tabs/index.js
This will fix issue https://github.com/jamesmfriedman/rmwc/issues/336
=> fix/Tabs: make conditional tabs work even after re-render

package-lock.json, src/list/docgen.json, src/list/index.js
Added existing class name 'mdc-list-item--disabled' to ListItemRoot in case disabled flag prop is provided. Added it among the consumable props.
Listed also disabled as prop in doc.  
Labeled as 'fix' since the class was already there in material css and, make sense to have it (multiple use cases in project I am currently working at).
=> fix(ListItem): added disabled state for Item in List

src/base/testPolyfill.js
=> Do not override canvas polyfill if already present

src/theme/utils.js
=> fix(theme): dark palette syntax error

src/select/index.js
Fixes: https://github.com/jamesmfriedman/rmwc/issues/387
=> fix(Select): use a combination of label and value as key for options

src/dialog/index.tsx
My attempt to fix #427 
If I missed something and it's easier for you to change it by yourself, feel free to close this pr.
=> Add action to typescript types for dialog

src/ripple/index.tsx
=> fix(Ripple): Fix ripple gets triggered twice on touch devices

src/rmwc/docs/README-INSTALLATION.md
Yeah, I know it's not the biggest PR you ever received but I observed that while reading the installation page and I throught..."well, why not?" :P
=> Fix typo on installation documentation

src/data-table/data-table.css
Hi!
I haven't actually built and tested this change (I just made the changes to my node_modules folder), but I figured that the easiest way to explain was just to write the code. Looks like you missed the word "text" from the variables and therefore the data table does not theme correctly.
Hope this is useful!
=> Fix data table theming

src/base/utils/get-display-name.tsx
Howdy! I upgraded to v6.0.2 and noticed a build-time error (my build logs: https://zeit.co/4cm4k1/personal-website/m6doong9t), so I went ahead and fixed it. Let me know if more is needed for this PR. Thanks! 😄
=> fix(Icon): Resolves build-time `TypeError: Cannot read property "name" of undefined`

package-lock.json, src/data-table/data-table.spec.tsx, src/data-table/data-table.story.tsx, src/data-table/index.tsx, src/data-table/package.json
You can now provide a click handler on `DataTableHeadCell` without passing `onSortedChange function` to manage sort `icon` of the `DataTable` fixes #624 and adds some a storybook file as well as some basic examples for the `DataTable`
=> fix(DataTable): datable controlled sorting #624

src/dialog/dialog-queue.tsx
=> Export DialogQueueSpec

src/tabs/tab-bar-foundation.tsx, src/tabs/tabs.spec.tsx
Before: 
After: 
https://github.com/jamesmfriedman/rmwc/issues/606
=> fix(Tab): activeTabIndex always updating automatically

src/select/select.story.tsx, src/select/select/foundation.tsx
Fixes https://github.com/jamesmfriedman/rmwc/issues/686 crash, but no idea if the root cause is on `rmwc` side or `mdn`
I also added a story to demonstrate the fix, since I am not that good with testing, but I assume that would preferred..? 
Is it okay to include all of that hook stuff in tests? I haven't seen tests for such situations in the repo select.spec file.
=> Simple dependent select crash fix

.github/workflows/unit-test.yml, src/doc-utils.tsx, src/select/select.spec.tsx, src/tabs/tabs.spec.tsx, src/textfield/textfield.spec.tsx
Fixed the remaining failing tests. Use react testing library instead of enzyme for the tests that were failing.
=> fix(test): Fixed failing tests

README.md, src/rmwc/docs/views/app/index.tsx, src/rmwc/docs/views/resources/index.tsx
- Removes references to contribution verbiage throughout
- Replaces image of my face on docs page with RMWC icon 
- Can't "Shut down" open collective without losing existing list of backers. Hid all of the contribution information on the profile page, updated the text , and removed all tiers.
=> Removing contribution verbiage

package-lock.json, package.json, src/select/__snapshots__/select.spec.tsx.snap, src/select/select/foundation.tsx
Controlled select did not work when enhanced. The issue was that we were getting the incorrect index. Fixed now! 
Also fixed another issue with tabIndex console error.
=> fix(select): Fix controlled enhanced select bug

src/list/list-item.css, src/list/list-item.tsx, src/list/styles.tsx, src/menu/README.md, src/menu/menu.spec.tsx, src/menu/readme.tsx
Fixes https://github.com/rmwc/rmwc/issues/847 by setting css pointer events to none.
=> fix(menu): Disable events when disabled is true

.github/workflows/scorecard.yml
https://docs.github.com/en/actions/security-guides/security-hardening-for-github-actions#using-third-party-actions
=> Create scorecard action to scan for risky supply chain practices

src/select/__snapshots__/select.spec.tsx.snap, src/select/readme.tsx, src/select/select.spec.tsx, src/select/select/index.tsx
Fixes https://github.com/rmwc/rmwc/issues/1011
=> fix(select): renderToPortal on enhanced menu

package-lock.json, package.json, src/checkbox/readme.tsx, src/data-table/readme.tsx, src/grid-list/readme.tsx, src/menu/readme.tsx, src/radio/readme.tsx, src/setupTests.ts, src/slider/readme.tsx, src/tabs/tab-bar-foundation.tsx, src/tabs/tab-scroller-foundation.tsx, src/tabs/tab-scroller.tsx, src/tooltip/README.md, src/tooltip/__snapshots__/tooltip.spec.tsx.snap, src/tooltip/foundation.tsx, src/tooltip/index.tsx, src/tooltip/readme.tsx, src/tooltip/tooltip-ssr.spec.tsx, src/tooltip/tooltip.spec.tsx, src/tooltip/tooltip.story.tsx
Renaming the prop `content` to `overlay` is going to be a breaking change, but it is clashing with some other props + typescript is complaining. Let me know if you think it is an acceptable change.
=> Readme fixes + little typescript update

packages/avatar/package.json, packages/badge/package.json, packages/chip/package.json, packages/circular-progress/package.json, packages/data-table/package.json, packages/icon/package.json, packages/list/package.json, packages/ripple/package.json, packages/select/package.json, packages/snackbar/package.json, packages/textfield/package.json, packages/theme/package.json, packages/tooltip/package.json
This ensures that css files are available via imports.
=> Export css files correctly

.envrc
=> Added direnv configuration

apps/docs/src/views/app/theme-picker.tsx, utils/readme/src/readmes/theme.tsx
Fixes https://github.com/rmwc/rmwc/issues/1182
=> fix(themes): make Shrine theme text accessible
